### ISSUE TITLE
JOSS: fix typos

### ISSUE THREAD

**Issue by sconde** [Nikoleta-v3/Game-Theory-and-Python#30]
Resolve the typos in the tutorial materials and paper.

**Comment by drvinceknight** [comment]
@sconde I've gone through the paper and notebooks and believe I've caught all the typos/errors in #31. I realise the PR diff on the notebook files is not ideal but if you have any further specific ones I've missed and could point them out it would be hugely appreciated.

**Comment by sconde** [comment]
Thank you so much

**Comment by drvinceknight** [comment]
Thank you for your review :+1:
